### ISSUE TITLE
WhisperNote attachment data not cleared after 2nd save

### ISSUE THREAD

**Issue by kubakk** [Consunet/Apps#38]
After an attachment is added, note is closed and then opened, if content is added again and note re-encrypted, the original attachment data is available after save even though other fields have been cleared.
This matters if the user doesn't close down the browser/tab after they are done.

**Comment by timConsunet** [comment]
While this has previously been fixed in the racc fork, this bug has now been fixed in the "CryptoChange" branch in commit: https://github.com/Consunet/Apps/commit/6f404317a383756781caa55ad29485552e9f8491

**Comment by racc** [comment]
Nice work @timConsunet :)
Hope your journey in understanding the messy pile of WhisperNote/EveryPass code was not too onerous...though it seems like you're doing ok +1
