### ISSUE TITLE
If timeout period set to 0 minutes, it makes the timeout clock look like -1:-1:-1

### ISSUE THREAD

**Issue by Adrian-Lambert** [Consunet/Apps#48]
Within options there is the ability to change the timeout period. It already has handling for if you try to set a negative timeout time, however when the timeout period is set to 0, it never times out and has a bugged display.

I believe a timeout period of 0 minutes should disable timeout, however the display should not be a negative time counter.

**Comment by kubakk** [comment]
Agree, timeout of 0 should disable the timeout counters.
Might be a good idea to warn a user about this too, its not a good idea to have no timeout.

**Comment by Adrian-Lambert** [comment]
The following code fixes the bug visually to stop it at 00:00:00 when timeout period is set to 0. I tried actually changing the time decrement function however it created another bug.

Replace setTimeoutString function within common/src/common.js:
```
setTimeoutString: function () {
       var minutes = this.padNum(Math.floor(this.timeoutValueSecs / 60.0) % 60);
        var hours = this.padNum(Math.floor(this.timeoutValueSecs / 3600.0));
        var secs = this.padNum(this.timeoutValueSecs % 60);
        if(secs<0 && this.getTimeout()!=0){
            secs=padNum(0);
        }
        if(hours<0){
            hours=padNum(0);
        }
        if(minutes<0){
            minutes=padNum(0);
        }
        var timeoutStr = hours + ":" + minutes + ":" + secs;
 // Make red if timeout is less than or equal to 30
        if (this.timeoutValueSecs <= 30) {
            this.addClass("timeout-value", "red");
        } else {
            this.removeClass("timeout-value", "red");
        }
 this.e("timeout-value").innerHTML = timeoutStr;
},
```

**Comment by kubakk** [comment]
Agree, timeout of 0 should disable the timeout counters.
Might be a good idea to warn a user about this too, its not a good idea to have no timeout.
