### ISSUE TITLE
Address security issues due to package-lock.json dependency.

### ISSUE THREAD

**Issue by kubakk** [Consunet/Apps#57]
Github reports that there are known security vulnerabilities in the package-lock.json. These should be addressed.

**Comment by Adrian-Lambert** [comment]
When I go to https://github.com/Consunet/Apps/network/dependencies, it does not show any security vulnerabilities messages. Is it possible to get more information about which dependency within package-lock.json is causing the issue?

**Comment by scottazord** [comment]
The package of concern is "hoek" which is used by "grunt-image-embed". Unfortunately grunt-image-embed hasn't seen any love in 4 years. In order to fix this security vulnerability, we would need to replace "grunt-image-embed' for a more modern library.

**Comment by scottazord** [comment]
This issue has been resolved.

Replaced library 'grunt-image-embed' with 'grunt-image-embed-src'.

The newer library has been forked from the original and updated to support a newer version of the request library.

Updated grunt-uncss to a later version to use a newer request library.
