### ISSUE TITLE
Tests Failing At odd occasions. 

### ISSUE THREAD

**Issue by scottazord** [Consunet/Apps#64]
The below tests are failing at odd times, timing issue?:
- Can do decrypt of encrypted file from final EveryPass build without grouping functionality (via import). 
- Can do decrypt of legacy (1.3) encrypted file via import.

**Comment by danielkoch86** [comment]
What I typically found with intermittent fails is that it was often due making for Selenium to do something on the page and not properly awaiting the automated action to be finished before moving on the next action or asserting a value or status of something. 
In summary make sure all Selenium calls are awaited as everything is asynchronous in Selenium.
